"""
Answer Evaluator Service for Mock Interview Mode
"""
import json
import re
from typing import Dict, List
from backend.groq_client import GroqClient

class AnswerEvaluator:
    """Service for evaluating candidate answers in Mock Interview mode"""
    
    def __init__(self, groq_client: GroqClient):
        self.groq_client = groq_client
        self.model = groq_client.model

    def evaluate_answer(
        self,
        question: str,
        expected_answer: str,
        candidate_answer: str,
        job_role: str,
        experience_level: str
    ) -> Dict:
        """
        Evaluate a candidate's answer to an interview question
        
        Args:
            question: The interview question
            expected_answer: The reference answer generated by AI
            candidate_answer: The answer candidate typed
            job_role: The targeted role
            experience_level: The candidate experience level
            
        Returns:
            Dictionary containing accuracy, relevance, completeness, clarity scores, and feedback
        """
        if not candidate_answer.strip():
            return {
                "technical_accuracy": 0,
                "relevance": 0,
                "completeness": 0,
                "clarity": 0,
                "overall": 0,
                "feedback": "No answer was provided."
            }

        prompt = f"""You are an expert interviewer. Evaluate the candidate's answer for the following interview question.

Job Role: {job_role}
Experience Level: {experience_level}
Interview Question: {question}
Ideal Reference Answer: {expected_answer}
Candidate's Answer: {candidate_answer}

Provide a structured assessment of the candidate's answer in valid JSON format.
Each score must be an integer between 0 and 10.

Return ONLY valid JSON with NO markdown or code blocks:
{{
  "technical_accuracy": <0-10>,
  "relevance": <0-10>,
  "completeness": <0-10>,
  "clarity": <0-10>,
  "overall": <0-10>,
  "feedback": "<detailed feedback on strengths and improvement areas>"
}}
"""
        try:
            response = self.groq_client.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a professional technical interviewer. You evaluate candidate answers accurately and return feedback in strict JSON format."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.3,
                max_tokens=1024
            )
            content = response.choices[0].message.content
            return self._parse_evaluation(content)
        except Exception as e:
            return {
                "technical_accuracy": 5,
                "relevance": 5,
                "completeness": 5,
                "clarity": 5,
                "overall": 5,
                "feedback": f"Could not perform AI evaluation due to an API error: {str(e)}. (Self-graded default)"
            }

    def generate_interview_summary(self, history: list) -> Dict:
        """
        Generate final summary of the interview performance
        
        Args:
            history: List of dictionaries detailing questions and scores
            
        Returns:
            Dictionary containing lists of strengths and areas to improve
        """
        if not history:
            return {
                "strengths": ["Completed the interview session"],
                "improvements": ["Try practicing more questions to get detailed AI summary analysis"]
            }

        # Format history for prompt
        formatted_history = ""
        for idx, item in enumerate(history, 1):
            formatted_history += f"Question {idx}: {item.get('question')}\nCandidate Answer: {item.get('candidate_answer')}\nScores: Accuracy={item.get('technical_accuracy')}/10, Relevance={item.get('relevance')}/10, Completeness={item.get('completeness')}/10, Clarity={item.get('clarity')}/10\nFeedback: {item.get('feedback')}\n\n"

        prompt = f"""Summarize this candidate's interview performance. Identify key technical strengths and areas to improve based on their performance history.

Performance History:
{formatted_history}

Return ONLY valid JSON with NO markdown or code blocks:
{{
  "strengths": ["Strength 1", "Strength 2", ...],
  "improvements": ["Area 1", "Area 2", ...]
}}
"""
        try:
            response = self.groq_client.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a technical recruiter. Summarize the interview performance into list of strengths and improvements in valid JSON."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.3,
                max_tokens=1024
            )
            content = response.choices[0].message.content
            return self._parse_summary(content)
        except Exception:
            return {
                "strengths": ["Completed the interview session"],
                "improvements": ["Try practicing more questions to get detailed AI summary analysis"]
            }

    def _parse_evaluation(self, content: str) -> Dict:
        content = content.strip()
        # Clean markdown code block if present
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', content, re.DOTALL)
        if json_match:
            content = json_match.group(1).strip()
        else:
            start = content.find('{')
            end = content.rfind('}')
            if start != -1 and end != -1:
                content = content[start:end+1]

        try:
            data = json.loads(content)
        except Exception:
            data = {}

        # Safe defaults and range checks
        def clean_score(val):
            try:
                score = int(float(val))
                return max(0, min(10, score))
            except Exception:
                return 5

        return {
            "technical_accuracy": clean_score(data.get("technical_accuracy", 5)),
            "relevance": clean_score(data.get("relevance", 5)),
            "completeness": clean_score(data.get("completeness", 5)),
            "clarity": clean_score(data.get("clarity", 5)),
            "overall": clean_score(data.get("overall", 5)),
            "feedback": str(data.get("feedback", "No feedback generated.")).strip()
        }

    def _parse_summary(self, content: str) -> Dict:
        content = content.strip()
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', content, re.DOTALL)
        if json_match:
            content = json_match.group(1).strip()
        else:
            start = content.find('{')
            end = content.rfind('}')
            if start != -1 and end != -1:
                content = content[start:end+1]

        try:
            data = json.loads(content)
            strengths = data.get("strengths", [])
            improvements = data.get("improvements", [])
            if isinstance(strengths, list) and isinstance(improvements, list):
                return {
                    "strengths": [str(s) for s in strengths if str(s).strip()],
                    "improvements": [str(i) for i in improvements if str(i).strip()]
                }
        except Exception:
            pass

        return {
            "strengths": ["Completed the interview session"],
            "improvements": ["Try practicing more questions to get detailed AI summary analysis"]
        }
